basic CRUD function for job management and related ut
TuGraph-family/tugraph-db-management pull request #1
Opened 2023-09-02 02:32 UTC by SonglinLyu

add handleCreateJobRequest function.

add handleReadJobRequest function.

add handleUpdateJobRequest function.

add handleDeleteJobRequest function.

add related unit test.

add ci.yml.

add check style plugin.

2023-09-04 09:29 UTC, qishipengqsp requested changes
总的来说，这么几方面吧
1. SQL字段定义规范问题
2. DAO是啥
3. POM规范问题
4. SQL templ Or SQL-ORM问题
5. 接口设计的一些问题，比如result接口建议单独拆开

2023-09-04 09:29 UTC, qishipengqsp commented on .mvn/wrapper/maven-wrapper.jar
这是什么？

2023-09-04 09:29 UTC, qishipengqsp commented on .mvn/wrapper/maven-wrapper.properties
这是什么？

2023-09-04 09:29 UTC, qishipengqsp commented on README.md
补充一下readme

2023-09-04 09:29 UTC, qishipengqsp commented on README_CN.md
补充一下readme

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
这个缩进怎么有点儿奇怪？一般是2个？checkstyle没问题么？

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
> +	<groupId>com.antgroup</groupId>
com.antgroup.tugraph

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
这个文件不太规范，后面如果发版到中央仓库的时候，会出问题，参考 https://github.com/TuGraph-family/tugraph-db-client-java 的pom改一下吧。比如url organziation scm developers这些标签

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/TugraphManagementApplication.java
> +public class TugraphManagementApplication {
Naming改一下TuGraphDBManagementApplication

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
> +		<java.version>1.8</java.version>
这个值需要在某个地方用一下

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
> +					<encoding>${project.build.sourceEncoding}</encoding>
这个缩进。。。

2023-09-04 09:29 UTC, qishipengqsp commented on pom.xml
以及我试了一下，这个在idea里面不能导入识别为spring项目？（springboot的示例项目可以，差别在哪里？）

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/JobDao.java
Dao是个什么naming?

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private String dbId;
实际存的是IP？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private String startTime;
存成string怎么查呢？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private Integer jobId;
jobId自增么？一般做法是弄一个uuid

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
字段定义问题不少，一般是这么几个原则：
1. 字段定义尽量紧凑，估算好长度，比如String(10)比string就好一些
2. 加点儿注释，说明字段含义，提高维护性
3. 字段类型定义尽量考虑一下查询效率，比如time这种，考虑用datetime类型还是epochtime作为Int比较

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/jdbc/impl/JobDaoImpl.java
> +    public int create(JobStatus jobStatus) {
这种裸的sql templ写的挺繁琐的，应该有类似orm的用法？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/service/impl/JobManagementServiceImpl.java
> +            new JobStatus()
从这个调用逻辑来看，这个表叫job比jobStatus好

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/resources/application.properties
> +spring.application.name=TuGraph Management
naming对应着修改一下

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:sqlite:tugraph_management.db
naming对应着修改一下

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
proto这个项目应该不用？主要是给cpp那边的？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/java/com/antgroup/tugraph/service/impl/JobManagementServiceImpl.java
> +            break;
这个缩进真的用了checkstyle了么。。？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
> +      required string creator = 9;
一般叫user吧，和creator还是不一样的

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
> +            ReadJobRequest read_job_request = 2;
感觉ReadResult单走一个接口好一些，也方便调

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
> +      optional int32 job_id = 2;
这个为什么optional？可能创建失败？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
> +      optional int32 job_id = 2;
以及也应该返回errorcode？

2023-09-04 09:29 UTC, qishipengqsp commented on src/main/proto/tugraph_management.proto
> +      enum ErrorCode {
规范上来说
1. 这个应该单独拎出去，所有的response里面都有这个。
2. Naming应该叫responseCode
3. 具备可扩展性，比如后续我们要加各种错误码

2023-09-04 09:29 UTC, qishipengqsp commented on src/test/java/com/antgroup/tugraph/TugraphManagementApplicationTests.java
> +	void testJobManagementService() {
测试前应该clean一下sqlite的文件？

2023-09-04 09:30 UTC, qishipengqsp commented
另外给github的ci 配置加点儿参数，现在ci的日志比较多，去掉一些无用的信息比如download maven包

2023-09-07 03:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TuGraph-family/tugraph-db-management?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TuGraph-family/tugraph-db-management?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TuGraph-family/tugraph-db-management?pullRequest=1) it.</sub>

2023-09-08 02:09 UTC, SonglinLyu commented on src/test/java/com/antgroup/tugraph/TugraphManagementApplicationTests.java
> +	void testJobManagementService() {
添加了clean所有table的操作

2023-09-08 02:12 UTC, SonglinLyu commented on src/main/proto/tugraph_management.proto
> +      optional int32 job_id = 2;
已修改为required

2023-09-08 02:12 UTC, SonglinLyu commented on src/main/proto/tugraph_management.proto
> +            ReadJobRequest read_job_request = 2;
修改为两个接口，ReadJobStatusRequest和ReadJobResultRequest

2023-09-08 02:20 UTC, SonglinLyu commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
emmm,奇怪了，我在vscode上看我服务器的文件不长这样，这是什么格式的bug吗？

2023-09-09 02:54 UTC, SonglinLyu commented on .mvn/wrapper/maven-wrapper.properties
不是我加的，可能是springboot空项目自带的？

2023-09-09 02:54 UTC, SonglinLyu commented on README.md
已补充中文版

2023-09-09 02:54 UTC, SonglinLyu commented on README_CN.md
已补充

2023-09-09 02:55 UTC, SonglinLyu commented on src/main/proto/tugraph_management.proto
> +      optional int32 job_id = 2;
error code已经提issue了，后面改

2023-09-10 03:26 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private String dbId;
添加注释

2023-09-10 03:28 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private Integer jobId;
jobId放到第一个

2023-09-10 17:17 UTC, SonglinLyu commented on pom.xml
> +		<java.version>1.8</java.version>
这个好像是springboot空项目自带的，查了一下是给maven指定java版本的

2023-09-10 17:17 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/TugraphManagementApplication.java
> +public class TugraphManagementApplication {
已改

2023-09-10 17:18 UTC, SonglinLyu commented on pom.xml
这个我还没试过，不过这个是在springboot官网生成的空项目的基础上改的，会不会是因为我们改成sofaboot了？

2023-09-10 17:20 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/jdbc/impl/JobDaoImpl.java
> +    public int create(JobStatus jobStatus) {
加到issue里了

2023-09-10 17:22 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private String startTime;
已改成int64，epoch time

2023-09-10 17:39 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/service/impl/JobManagementServiceImpl.java
> +            new JobStatus()
JobStatus 都改成 Job 了

2023-09-10 17:50 UTC, SonglinLyu commented on src/main/java/com/antgroup/tugraph/jdbc/JobStatus.java
> +    private String dbId;
表项的注释以添加

2023-09-11 02:50 UTC, qishipengqsp approved these changes

2023-09-11 02:54 UTC, merged